- name: Run tests with pytest
  run: |
    cd rag-app
    OPENAI_API_KEY=dummy-key \
    OPENAI_MODEL=gpt-3.5-turbo \
    environment=local \
    app_name=rag-app \
    debug=true \
    postgres_host=localhost \
    postgres_db=rag \
    postgres_user=rag_user \
    postgres_password=pass \
    arxiv_api_url=https://example.com \
    data_path=papers-downloads \
    temperature=0.7 \
    top_p=1.0 \
    max_tokens=256 \
    opik_api_key=abc \
    opik_workspace=test \
    opik_project_name=test \
    poetry run pytest
