name: CI with Pytest

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "::add-path::/home/runner/.local/bin"

      - name: Install dependencies with Poetry
        run: |
          cd rag-app
          poetry install

      - name: Run tests with pytest
        run: |
          cd rag-app
          poetry run pytest
